# Generated by Django 5.2 on 2025-05-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="bytes",
        ),
        migrations.AddField(
            model_name="file",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("AVATAR", "Avatar"),
                    ("CV", "CV"),
                    ("LOGO", "Logo"),
                    ("COVER_IMAGE", "Cover Image"),
                    ("COMPANY_IMAGE", "Company Image"),
                    ("CAREER_IMAGE", "Career Image"),
                    ("WEB_BANNER", "Web Banner"),
                    ("MOBILE_BANNER", "Mobile Banner"),
                    ("SYSTEM", "System"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
        migrations.AlterModelTable(
            name="file",
            table="myjob_files",
        ),
    ]
