# Generated by Django 5.2 on 2025-05-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_remove_file_bytes_file_file_type_alter_file_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="file",
            table="findjob_files",
        ),
    ]
