# Generated by Django 5.2 on 2025-04-20 04:03

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import django.utils.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='company_name', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('company_image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('company_image_public_id', models.CharField(blank=True, max_length=300, null=True)),
                ('company_cover_image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('company_cover_image_public_id', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_email', models.EmailField(max_length=100, unique=True)),
                ('company_phone', models.CharField(max_length=15, unique=True)),
                ('website_url', models.URLField(blank=True, max_length=300, null=True)),
                ('tax_code', models.CharField(max_length=30, unique=True)),
                ('since', models.DateField(null=True)),
                ('field_operation', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('employee_size', models.SmallIntegerField(choices=[(1, 'Dưới 10 nhân viên'), (2, '10 - 150 nhân viên'), (3, '150 - 300 nhân viên'), (4, 'Trên 300 nhân viên')], null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='common.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'findjob_info_company',
            },
        ),
        migrations.CreateModel(
            name='CompanyFollowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies followed',
                'db_table': 'findjob_info_company_followed',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(related_name='companies_followed', through='info.CompanyFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_images', to='info.company')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_image', to='common.file')),
            ],
            options={
                'db_table': 'findjob_info_company_image',
            },
        ),
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True)),
                ('marital_status', models.CharField(choices=[('S', 'Độc thân'), ('M', 'Đã kết hôn')], default='S', max_length=1, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_seeker_profiles', to='common.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'findjob_info_job_seeker_profile',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('description', models.TextField(null=True)),
                ('salary_min', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('salary_max', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('position', models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')], null=True)),
                ('experience', models.SmallIntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, 'Dưới 1 năm kinh nghiệm '), (3, '1 năm kinh nghiệm'), (4, '2 năm kinh nghiệm'), (5, '3 năm kinh nghiệm'), (6, '4 năm kinh nghiệm'), (7, '5 năm kinh nghiệm'), (8, 'Trên 5 năm kinh nghiệm')], null=True)),
                ('academic_level', models.SmallIntegerField(choices=[(1, 'Trên Đại học'), (2, 'Đại học'), (3, 'Cao đẳng'), (4, 'Trung cấp'), (5, 'Trung học'), (6, 'Chứng chỉ')], null=True)),
                ('type_of_workplace', models.SmallIntegerField(choices=[(1, 'Làm việc tại văn phòng'), (2, 'Làm việc kết hợp'), (3, 'Làm việc tại nhà')], null=True)),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Toàn thời gian cố định'), (2, 'Toàn thời gian tạm thời'), (3, 'Bán thời gian cố định'), (4, 'Bán thời gian tạm thời'), (5, 'Theo hợp đồng tư vấn'), (6, 'Thực tập'), (7, 'Khác')], null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('type', models.CharField(default='UPLOAD', max_length=10)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='common.city')),
                ('file', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_file', to='common.file')),
                ('job_seeker_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='info.jobseekerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'findjob_info_resume',
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('language', models.SmallIntegerField(choices=[(1, 'Việt Nam'), (2, 'Anh'), (3, 'Nhật Bản'), (4, 'Pháp'), (5, 'Trung Quốc'), (6, 'Nga'), (7, 'Hàn Quốc'), (8, 'Đức'), (9, 'Ý'), (10, 'Ả Rập'), (11, 'Khác')])),
                ('level', models.SmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='info.resume')),
            ],
            options={
                'db_table': 'findjob_info_language_skill',
            },
        ),
        migrations.CreateModel(
            name='ExperienceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_details', to='info.resume')),
            ],
            options={
                'db_table': 'findjob_info_experience_detail',
            },
        ),
        migrations.CreateModel(
            name='EducationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('degree_name', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=255)),
                ('training_place_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('completed_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='info.resume')),
            ],
            options={
                'db_table': 'findjob_info_education_detail',
            },
        ),
        migrations.CreateModel(
            name='ContactProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Contact profiles',
                'db_table': 'findjob_info_contact_profile',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('training_place', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='info.resume')),
            ],
            options={
                'db_table': 'findjob_info_certificate',
            },
        ),
        migrations.CreateModel(
            name='AdvancedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.SmallIntegerField(default=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advanced_skills', to='info.resume')),
            ],
            options={
                'db_table': 'findjob_info_advanced_skill',
            },
        ),
        migrations.CreateModel(
            name='ResumeSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Resumes saved',
                'db_table': 'findjob_info_resume_saved',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='company_savers',
            field=models.ManyToManyField(related_name='resumes_saved', through='info.ResumeSaved', to='info.company'),
        ),
        migrations.CreateModel(
            name='ResumeViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('views', models.BigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.company')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
            ],
            options={
                'verbose_name_plural': 'Resumes viewed',
                'db_table': 'findjob_info_resume_viewed',
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='company_viewers',
            field=models.ManyToManyField(related_name='resumes_viewed', through='info.ResumeViewed', to='info.company'),
        ),
    ]
