# Generated by Django 5.2 on 2025-04-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_cover_image_public_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_cover_image_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_image_public_id',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_image_url',
        ),
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_cover_image', to='common.file'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logo', to='common.file'),
        ),
        migrations.AlterModelTable(
            name='advancedskill',
            table='myjob_info_advanced_skill',
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='myjob_info_certificate',
        ),
        migrations.AlterModelTable(
            name='company',
            table='myjob_info_company',
        ),
        migrations.AlterModelTable(
            name='companyfollowed',
            table='myjob_info_company_followed',
        ),
        migrations.AlterModelTable(
            name='companyimage',
            table='myjob_info_company_image',
        ),
        migrations.AlterModelTable(
            name='contactprofile',
            table='myjob_info_contact_profile',
        ),
        migrations.AlterModelTable(
            name='educationdetail',
            table='myjob_info_education_detail',
        ),
        migrations.AlterModelTable(
            name='experiencedetail',
            table='myjob_info_experience_detail',
        ),
        migrations.AlterModelTable(
            name='jobseekerprofile',
            table='myjob_info_job_seeker_profile',
        ),
        migrations.AlterModelTable(
            name='languageskill',
            table='myjob_info_language_skill',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='myjob_info_resume',
        ),
        migrations.AlterModelTable(
            name='resumesaved',
            table='myjob_info_resume_saved',
        ),
        migrations.AlterModelTable(
            name='resumeviewed',
            table='myjob_info_resume_viewed',
        ),
    ]
