# Generated by Django 5.2 on 2025-04-20 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_company_company_cover_image_public_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advancedskill',
            table='findjob_info_advanced_skill',
        ),
        migrations.AlterModelTable(
            name='certificate',
            table='findjob_info_certificate',
        ),
        migrations.AlterModelTable(
            name='company',
            table='findjob_info_company',
        ),
        migrations.AlterModelTable(
            name='companyfollowed',
            table='findjob_info_company_followed',
        ),
        migrations.AlterModelTable(
            name='companyimage',
            table='findjob_info_company_image',
        ),
        migrations.AlterModelTable(
            name='contactprofile',
            table='findjob_info_contact_profile',
        ),
        migrations.AlterModelTable(
            name='educationdetail',
            table='findjob_info_education_detail',
        ),
        migrations.AlterModelTable(
            name='experiencedetail',
            table='findjob_info_experience_detail',
        ),
        migrations.AlterModelTable(
            name='jobseekerprofile',
            table='findjob_info_job_seeker_profile',
        ),
        migrations.AlterModelTable(
            name='languageskill',
            table='findjob_info_language_skill',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='findjob_info_resume',
        ),
        migrations.AlterModelTable(
            name='resumesaved',
            table='findjob_info_resume_saved',
        ),
        migrations.AlterModelTable(
            name='resumeviewed',
            table='findjob_info_resume_viewed',
        ),
    ]
