# Generated by Django 5.2 on 2025-04-20 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('button_text', models.TextField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('is_show_button', models.BooleanField(default=False)),
                ('description_location', models.IntegerField(choices=[(1, 'TOP_LEFT'), (2, 'TOP_RIGHT'), (3, 'BOTTOM_LEFT'), (4, 'BOTTOM_RIGHT')], default=3)),
                ('platform', models.CharField(choices=[('WEB', 'Website'), ('APP', 'Ứng dụng')], default=1, max_length=3)),
                ('type', models.IntegerField(choices=[(1, 'HOME'), (2, 'MAIN_JOB_RIGHT')], default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image', to='common.file')),
                ('image_mobile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_image_mobile', to='common.file')),
            ],
            options={
                'db_table': 'findjob_findjob_banner',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=500)),
                ('rating', models.SmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'findjob_findjob_feedback',
            },
        ),
    ]
