# Generated by Django 5.2 on 2025-05-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findjob", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="imageUrl",
            field=models.BooleanField(default=False),
        ),
    ]
