# Generated by Django 5.2 on 2025-05-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findjob", "0002_banner_imageurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="imageUrl",
            field=models.URLField(blank=True, null=True),
        ),
    ]
