# Generated by Django 5.2 on 2025-05-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("findjob", "0003_alter_banner_imageurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="banner",
            old_name="imageUrl",
            new_name="image_url",
        ),
    ]
