# Generated by Django 5.2 on 2025-04-20 04:03

import autoslug.fields
import ckeditor.fields
import django.db.models.deletion
import django.utils.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=300, populate_from='job_name', slugify=django.utils.text.slugify, unique_with=['id'])),
                ('deadline', models.DateField()),
                ('quantity', models.IntegerField()),
                ('gender_required', models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, null=True)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('job_requirement', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('benefits_enjoyed', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('position', models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')])),
                ('type_of_workplace', models.SmallIntegerField(choices=[(1, 'Làm việc tại văn phòng'), (2, 'Làm việc kết hợp'), (3, 'Làm việc tại nhà')])),
                ('experience', models.SmallIntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, 'Dưới 1 năm kinh nghiệm '), (3, '1 năm kinh nghiệm'), (4, '2 năm kinh nghiệm'), (5, '3 năm kinh nghiệm'), (6, '4 năm kinh nghiệm'), (7, '5 năm kinh nghiệm'), (8, 'Trên 5 năm kinh nghiệm')])),
                ('academic_level', models.SmallIntegerField(choices=[(1, 'Trên Đại học'), (2, 'Đại học'), (3, 'Cao đẳng'), (4, 'Trung cấp'), (5, 'Trung học'), (6, 'Chứng chỉ')])),
                ('job_type', models.SmallIntegerField(choices=[(1, 'Toàn thời gian cố định'), (2, 'Toàn thời gian tạm thời'), (3, 'Bán thời gian cố định'), (4, 'Bán thời gian tạm thời'), (5, 'Theo hợp đồng tư vấn'), (6, 'Thực tập'), (7, 'Khác')])),
                ('salary_min', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('is_hot', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Chờ duyệt'), (2, 'Không duyệt'), (3, 'Đã duyệt')], default=1)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_phone', models.CharField(max_length=15)),
                ('contact_person_email', models.EmailField(max_length=100)),
                ('views', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='common.career')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='info.company')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to='common.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'findjob_job_job_post',
            },
        ),
        migrations.CreateModel(
            name='JobPostActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Chờ xác nhận'), (2, 'Đã liên hệ'), (3, 'Đã test'), (4, 'Đã phỏng vấn'), (5, 'Trúng tuyển'), (6, 'Không trúng tuyển')], default=1)),
                ('is_sent_email', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='info.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job posts activity',
                'db_table': 'findjob_job_job_post_activity',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='peoples_applied',
            field=models.ManyToManyField(related_name='job_posts_activity', through='job.JobPostActivity', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobPostNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=255)),
                ('position', models.SmallIntegerField(choices=[(1, 'Quản lý cấp cao'), (2, 'Quản lý cấp trung'), (3, 'Quản lý nhóm- giám sát'), (4, 'Chuyên gia'), (5, 'Chuyên viên- nhân viên'), (6, 'Cộng tác viên')], null=True)),
                ('experience', models.SmallIntegerField(choices=[(1, 'Chưa có kinh nghiệm'), (2, 'Dưới 1 năm kinh nghiệm '), (3, '1 năm kinh nghiệm'), (4, '2 năm kinh nghiệm'), (5, '3 năm kinh nghiệm'), (6, '4 năm kinh nghiệm'), (7, '5 năm kinh nghiệm'), (8, 'Trên 5 năm kinh nghiệm')], null=True)),
                ('salary', models.IntegerField(null=True)),
                ('frequency', models.IntegerField(choices=[(1, 'Mỗi ngày'), (2, '3 Ngày / lần'), (3, '1 Tuần / 1 lần')])),
                ('is_active', models.BooleanField(default=False)),
                ('career', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='common.career')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post_notifications', to='common.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job post notifications',
                'db_table': 'findjob_job_job_post_notification',
            },
        ),
        migrations.CreateModel(
            name='SavedJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved job posts',
                'db_table': 'findjob_job_saved_job_post',
            },
        ),
        migrations.AddField(
            model_name='jobpost',
            name='peoples_saved',
            field=models.ManyToManyField(related_name='saved_job_posts', through='job.SavedJobPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
